version: "3.9"

services:
  db:
    build: .
    container_name: recur-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recur
    ports:
      - "5436:5432"
    volumes:
      - recur-db-data:/var/lib/postgresql/data

volumes:
  recur-db-data: